### ISSUE TITLE
Conflicting message about having an error 

### ISSUE THREAD

**Issue by jefflord** [coinzdude/javascript-errors-notifier#2] opened 2023-03-11 23:43 UTC
At this URL, https://www.google.com/search?q=designer.microsoft

![image](https://user-images.githubusercontent.com/4396667/224516508-7e8dc4c4-1fa9-46f9-a344-18fae525961d.png)

The icon at the bottom shows when there is no error.

**Comment by coinzdude** [comment] 2023-03-14 04:22
Would you please retest? I did not make any specific changes for this, but I cannot reproduce.

This page appears to have no errors, and I am not getting an alert, as expected.

![image](https://user-images.githubusercontent.com/58857646/224892598-b78a1526-35c7-4f6c-9b6e-1a711f41317c.png)

**Comment by coinzdude** [comment] 2023-03-16 02:11
I think this was resolved by fixing the options storage state issues

**Closed as completed by coinzdude** 2023-03-16 02:11 UTC
